registered panic handler
causing panic...
inside raiser.raiser...
caught raiser.raiser_error
[0] pass: caught exception
