registered panic handler
causing panic...
inside Raiser.Raiser...
Caught Raiser.Raiser_Error
[0] Pass: Caught exception
